### ISSUE TITLE
DEFECTO 19 - CYC - CONSULTAR

### ISSUE THREAD

**Issue by ivantrujillo79** [TransformaTI/SigametLibrerias#19]
## Descripción
Con parametro Gateway, al momento de dar clic en Consultar la página se queda congelada y despues muestra el siguiente mensaje de error

## Evidencias
![image.png](https://images.zenhubusercontent.com/59a050988f62dc7798c4133f/da0cd5d5-9d31-45df-b9e2-620d9960fbe2)

https://drive.google.com/file/d/1pDL6mzB70vHeDxtdg9soTKyy3bAgfqsu/view

**Comment by HMP80** [comment]
Este problema es provocado por el que el Gateway no esta devolviendo nada. Tal vez esta fallando el Webservice.




________________________________
De: Iván Trujillo <notifications@github.com>
Enviado: lunes, 23 de julio de 2018 01:23 p. m.
Para: TransformaTI/SigametLibrerias
CC: HMP80; Assign
Asunto: [TransformaTI/SigametLibrerias] DEFECTO 19 - CYC - CONSULTAR (#19)

Descripción

Con parametro Gateway, al momento de dar clic en Consultar la página se queda congelada y despues muestra el siguiente mensaje de error

Evidencias

[image.png]<https://camo.githubusercontent.com/082903c6c64f207ab83ad244c6f4c82b096dd684/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3539613035303938386636326463373739386334313333662f64613063643564352d396433312d343564662d623965322d363230643939363066626532>
